/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.openfga.kotlin.client.models

import dev.openfga.kotlin.client.models.ObjectRelation

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tupleset 
 * @param computedUserset 
 */

data class TupleToUserset (

    @Json(name = "tupleset")
    val tupleset: ObjectRelation? = null,

    @Json(name = "computedUserset")
    val computedUserset: ObjectRelation? = null

)

