/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.openfga.kotlin.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: wRITE,dELETE
 */

enum class TupleOperation(val value: kotlin.String) {

    @Json(name = "TUPLE_OPERATION_WRITE")
    wRITE("TUPLE_OPERATION_WRITE"),

    @Json(name = "TUPLE_OPERATION_DELETE")
    dELETE("TUPLE_OPERATION_DELETE");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TupleOperation) "$data" else null

        /**
         * Returns a valid [TupleOperation] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TupleOperation? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

