/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.ozee.openfga.client.models

import io.ozee.openfga.client.models.Leaf
import io.ozee.openfga.client.models.Nodes
import io.ozee.openfga.client.models.UsersetTreeDifference

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param leaf 
 * @param difference 
 * @param union 
 * @param intersection 
 */

data class Node (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "leaf")
    val leaf: Leaf? = null,

    @Json(name = "difference")
    val difference: UsersetTreeDifference? = null,

    @Json(name = "union")
    val union: Nodes? = null,

    @Json(name = "intersection")
    val intersection: Nodes? = null

)

