/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.ozee.openfga.client.models

import io.ozee.openfga.client.models.Tuple

import com.squareup.moshi.Json

/**
 * 
 *
 * @param tuples 
 * @param continuationToken 
 */

data class ReadResponse (

    @Json(name = "tuples")
    val tuples: kotlin.collections.List<Tuple>? = null,

    @Json(name = "continuation_token")
    val continuationToken: kotlin.String? = null

)

