/**
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.ozee.openfga.client.models

import io.ozee.openfga.client.models.TupleKeys

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param writes 
 * @param deletes 
 * @param authorizationModelId 
 */

data class WriteRequest (

    @Json(name = "writes")
    val writes: TupleKeys? = null,

    @Json(name = "deletes")
    val deletes: TupleKeys? = null,

    @Json(name = "authorization_model_id")
    val authorizationModelId: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

